site_name: 'SmartOS Docs'
repo_name: 'joyent/smartos-live'
repo_url: 'https://github.com/joyent/smartos-live'
edit_uri: '/joyent/smartos-docs/edit/master/docs/'

theme:
    name: null
    custom_dir: material-smartos
    palette:
        primary: indigo
        accent: light blue
    language: en
    font:
        text: Open Sans
        code: Open Mono
    logo: assets/images/smartos-logo.svg
    feature:
        tabs: false
    include_search_page: true
    search_index_only: false

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: true

nav:
    - 'Home': 'index.md'
    - 'Welcome to SmartOS':
        - 'SmartOS Quick Start Guide': 'smartos-quick-start-guide.md'
        - 'SmartOS Technical FAQs': 'smartos-technical-faqs.md'
        - 'illumos and SmartOS Basics': 'illumos-and-smartos-basics.md'
        - 'Why SmartOS - ZFS, KVM, DTrace, Zones and More': 'why-smartos-zfs-kvm-dtrace-zones-and-more.md'
    - 'Installing SmartOS':
        - 'Download SmartOS': 'download-smartos.md'
        - 'Creating a SmartOS Bootable USB Key': 'creating-a-smartos-bootable-usb-key.md'
        - 'SmartOS as a VMware Guest': 'smartos-as-a-vmware-guest.md'
        - 'SmartOS as a VirtualBox Guest': 'smartos-as-a-virtualbox-guest.md'
        - 'PXE Booting SmartOS': 'pxe-booting-smartos.md'
        - 'Installation Walkthrough': 'install.md'
    - 'SmartOS Core Technologies':
        - 'Overview': 'smartos-core-technologies.md'
        - 'Performance': 'performance.md'
        - 'Virtualization':
            - 'Overview': 'smartos-virtualization.md'
            - 'Zones': 'zones.md'
            - 'KVM': 'kvm.md'
            - 'Bhyve': 'bhyve.md'
        - 'ZFS': 'zfs.md'
        - 'Networking and Network Virtualization': 'networking-and-network-virtualization.md'
        - 'SMF - Service Management Facility': 'basic-smf-commands.md'
        - 'DTrace': 'dtrace.md'
        - 'Modular Debugger (mdb)': 'mdb.md'
    - 'SmartOS Users Guide':
        - 'Overview': 'smartos-users-guide.md'
        - 'Getting Started with SmartOS': 'getting-started-with-smartos.md'
        - 'Administering the Global Zone': 'administering-the-global-zone.md'
        - 'Managing Images': 'managing-images.md'
        - 'How to create a zone': 'how-to-create-a-zone.md'
        - 'How to create a HVM VM': 'how-to-create-an-hvm-zone.md'
        - 'How to create a Virtual Machine From Scratch': 'how-to-create-a-virtual-machine-from-scratch.md'
        - 'Managing instances': 'managing-instances-with-vmamd.md'
        - 'Changing the Root Password in the Global Zone': 'changing-the-root-password-in-the-global-zone.md'
        - 'Managing NICs': 'managing-nics.md'
        - 'Working with Packages': 'working-with-packages.md'
        - 'Using the Service Management Facility': 'basic-smf-commands.md'
        - 'Debugging problems': 'debugging.md'
        - 'SmartOS Command Line Tips': 'smartos-command-line-tips.md'
        - 'Configuration Management on SmartOS':
            - 'Overview': 'configuration-management-on-smartos.md'
            - 'Persistent Configuration for the Global Zone': 'persistent-configuration-for-the-global-zone.md'
            - 'Modifying Kernel Boot Files': 'modifying-boot-files.md'
            - 'Using Ansible': 'using-ansible.md'
            - 'Using Chef': 'using-chef.md'
            - 'Using Puppet': 'using-puppet.md'
        - 'References': 'references.md'
        - 'Configuring NFS in SmartOS': 'configuring-nfs-in-smartos.md'
        - 'Configuring SMB in SmartOS': 'configuring-smb-in-smartos.md'
        - 'Changing virtual hardware of KVM zones': 'changing-virtual-hardware-of-kvm-zones.md'
        - 'Extra Configuration Options': 'extra-configuration-options.md'
        - 'Glossary': 'illumos-and-smartos-basics/glossary.md'
    - 'SmartOS Developers Guide':
        - 'Overview': 'smartos-developers-guide.md'
        - 'Extending smartos-live': 'extending-smartos-live.md'
        - 'Building Individual Drivers in SmartOS': 'building-individual-drivers-in-smartos.md'
        - 'Porting Network Device Drivers from FreeBSD': 'porting-network-device-drivers-from-freebsd.md'
        - 'LX Branded Zones': 'lx-branded-zones.md'
        - 'Running SmartOS on OmniOS KVM': 'running-smartos-on-omnios-kvm.md'
    - 'The SmartOS Community':
        - 'Mailing Lists & IRC': 'mailing-lists-and-irc.md'
        - 'History': 'community-history.md'
        - 'Community Experiments': 'community-experiments.md'
        - 'Edit This Documentation': 'https://github.com/joyent/smartos-docs/'
