# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Copyright 2020 Joyent, Inc.
# Copyright 2024 MNX Cloud, Inc.

site_name: "SmartOS Documentation"
site_url: "https://docs.smartos.org/"
repo_name: "TritonDataCenter/smartos-live"
repo_url: "https://github.com/TritonDataCenter/smartos-live"
edit_uri: "/TritonDataCenter/smartos-docs/edit/master/docs/"

theme:
    name: "mkdocs"
    custom_dir: material-smartos
    palette:
        primary: indigo
        accent: light blue
    language: en
    font:
        text: Open Sans
        code: Open Mono
    logo: assets/images/smartos-logo.svg
    feature:
        tabs: false
    include_search_page: true
    search_index_only: false

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: true

nav:
    - "Home": "index.md"
    - "Quick Start Guide": "smartos-quick-start-guide.md"
    - "Download SmartOS": "download-smartos.md"
    - "SmartOS User's Guide":
        - "Installation":
            - "Download SmartOS": "download-smartos.md"
            - "Creating a SmartOS Bootable USB Key": "creating-a-smartos-bootable-usb-key.md"
            - "SmartOS as a VMware Guest": "smartos-as-a-vmware-guest.md"
            - "SmartOS as a VirtualBox Guest": "smartos-as-a-virtualbox-guest.md"
            - "SmartOS as a UTM Guest on Apple Silicon": "smartos-as-a-utm-guest.md"
            - "Installation Walkthrough": "install.md"
            - "Non-interactive Installation": "non-interactive-install.md"
        - "Getting Started with SmartOS": "getting-started-with-smartos.md"
        - "Installing the SmartOS Web UI": "web-interface.md"
        - "Virtual Instances":
            - "How to create a native SmartOS Instance": "how-to-create-a-zone.md"
            - "How to create a Hardware Virtual Machine": "how-to-create-an-hvm-zone.md"
            - "How to create a Linux container without a VM (LX Branded Zones)": "lx-branded-zones.md"
            - "Instance Management":
                - "Managing Instances with vmadm": "managing-instances-with-vmamd.md"
                - "Instance Metadata": "customer_metadata.md"
        - "Managing Images": "managing-images.md"
        - "Administering SmartOS Native Instances":
            - "Managing Packages": "working-with-packages.md"
            - "Managing Services": "smf-quick-reference.md"
            - "Configuring NFS in SmartOS": "configuring-nfs-in-smartos.md"
            - "Configuring SMB in SmartOS": "configuring-smb-in-smartos.md"
            - "SmartOS Core Technologies": "smartos-core-technologies.md"
        - "Administering The Hypervisor (Global Zone)":
            - "Introduction to the Hypervisor (aka, Global Zone)": "administering-the-global-zone.md"
            - "Persistent Configuration for the Global Zone": "persistent-configuration-for-the-global-zone.md"
            - "Extra Hypervisor Configuration Options": "extra-configuration-options.md"
            # - "Using the Service Management Facility": "basic-smf-commands.md"
            - "Managing Services": "smf-quick-reference-gz.md"
            - "Changing the Root Password in the Global Zone": "changing-the-root-password-in-the-global-zone.md"
            - "Managing NICs": "managing-nics.md"
        - "SmartOS Command Line Tips": "smartos-command-line-tips.md"
        - "Configuration Management on SmartOS":
            - "Overview": "configuration-management-on-smartos.md"
            - "Using Ansible": "using-ansible.md"
            - "Using CfEngine": "using-cfengine.md"
            - "Using Chef": "using-chef.md"
            - "Using Puppet": "using-puppet.md"
        - "Glossary": "illumos-and-smartos-basics/glossary.md"
        - "References": "references.md"
    - "Core Technologies":
        - "Technology Overview": "smartos-core-technologies.md"
        - "Performance": "performance.md"
        - "Virtualization":
            - "Machine Monitor Overview": "smartos-virtualization.md"
            - "Zones": "zones.md"
            - "KVM": "kvm.md"
            - "Bhyve": "bhyve.md"
        - "ZFS": "zfs.md"
        # - "Networking and Network Virtualization": "networking-and-network-virtualization.md"
        # - "SMF - Service Management Facility": "basic-smf-commands.md"
        - "DTrace": "dtrace.md"
        - "Modular Debugger (mdb)": "mdb.md"
    - "Advanced Topics":
        - "SmartOS Technical FAQs": "smartos-technical-faqs.md"
        - "illumos and SmartOS Basics": "illumos-and-smartos-basics.md"
        - "PXE Booting SmartOS": "pxe-booting-smartos.md"
        - "Modifying Kernel Boot Files": "modifying-boot-files.md"
        - "Configuring IPv6 for Instances": "setting-up-ipv6-in-a-zone.md"
        - "How to boot a Virtual Machine From an ISO": "how-to-create-a-virtual-machine-from-scratch.md"
    - "Developers Guide":
        - "Developer Overview": "smartos-developers-guide.md"
        - "Extending smartos-live": "extending-smartos-live.md"
        - "Building Individual Drivers in SmartOS": "building-individual-drivers-in-smartos.md"
        - "Porting Network Device Drivers from FreeBSD": "porting-network-device-drivers-from-freebsd.md"
        - "Running SmartOS on OmniOS KVM": "running-smartos-on-omnios-kvm.md"
        - "Debugging problems": "debugging.md"
        - "LX Brand Development": "lx-dev.md"
    - "The SmartOS Community":
        - "Code of Conduct": "CODE_OF_CONDUCT.md"
        - "Mailing Lists, Forums, and Chat": "mailing-lists-and-irc.md"
        - "History": "community-history.md"
        - "Community Experiments": "community-experiments.md"
        - "Edit This Documentation": "https://github.com/TritonDataCenter/smartos-docs/"
